export default {
	// AUTH
	LOGIN: "Login",
	REGISTER: "Register",
	FORGOT_PASSWORD: "Forgot Password",

	// HOME
	HOME: "Home",
	HOME_TAB: "Home Tab",

	// TRANSFER
	TRANSFER: "TRANSFER",
	TRANSFER_RECEIPIENT: "TRANSFER_RECEIPIENT",
	TRANSFER_TRANSACTION: "TRANSFER_TRANSACTION",
	TRANSFER_CONFIRMATION: "TRANSFER_CONFIRMATION",
	TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
	TRANSFER_TAB: "TRANSFER_TAB",
	PIN_VERIFY: "PIN_VERIFY",

	// ANALYTICS
	ANALYTICS: "Analytics",
	ANALYTICS_TAB: "Analytics Tab",

	// CONTACT
	CONTACT: "Contact",
	CONTACT_TAB: "Contact Tab",

	// NOTIFICATIONS
	NOTIFICATIONS: "Notifications",
	NOTIFICATIONS_TAB: "Notifications Tab",

	// PROFILE
	PROFILE: "Profile",
	PROFILE_TAB: "Profile Tab",
	PIN_MENU: "PIN_MENU",
	PIN_ENROLL: "PIN_ENROLL",
	PIN_MODIFY: "PIN_MODIFY",
	PIN_STATUS: "PIN_STATUS",
	DEVICES_LIST: "DEVICES_LIST",

	// GLOBAL
	SMS: "SMS",
};
